server:
  port: 8800

spring:
  application:
    name: cloud-stream-provider
  rabbitmq:
    host: 113.125.79.76
    port: 5672
    username: admin
    password: 123456
    virtual-host: my_vhost
    publisher-confirm-type: correlated
    publisher-returns: true
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
#          environment:
#            port: 5672 # 指定rabbitmq连接的端口号
#            virtual-host: my_vhost # 指定rabbitmq虚拟主机
#            host: 113.125.79.76 # 指定rabbitmq的主机名
#            username: admin # 用户名
#            password: 123456 # 密码
      bindings: # 服务的整合处理
        output: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: text/plain # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: defaultRabbit # 指定要使用的rabbitmq绑定

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: send-8801.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址







