server:
  port: 8005
spring:
  application:
    name: consul-provider-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
