server:
  port: 3344
spring:
  application:
    name: config-center-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/jinmoux/srping-config.git
          search-paths:
            - spring-config
          username: 760744855@qq.com
          password: q760744855
      label: master
  rabbitmq:
    host: 113.125.79.76
    port: 5672
    username: admin
    password: 123456
    virtual-host: my_vhost


#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
